# run gitlab, re-create the container if required
run:
  retry: 2
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker info
     - docker images
     - docker-compose up -d

# load the latest image from the docker registry,
# and if neccessary re-create the container
upgrade:
  retry: 2
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker info
     - docker images
     - docker-compose pull
     - docker-compose up -d

# stop and tear down containers
down:
  retry: 2
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker-compose down

# reload configuration
reload:
  retry: 2
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker-compose exec -T https-proxy bash -c 'nginx -s reload'

# restart containers
restart:
  retry: 2
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker-compose restart

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

