version: '3.5'

services:

  https-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST:-sammlungsraeume.de}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - logs:/var/log/nginx/ext
      - passwords:/etc/nginx/htpasswd:ro
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
    networks:
      default:
      proxy-network:
        aliases:
          - https-proxy

  le-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html

  netdata:
    image: nginx:alpine
    restart: always
    environment:
       VIRTUAL_HOST: leo-status.halle.tech
       LETSENCRYPT_HOST: leo-status.halle.tech
       LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
       BEHIND_PROXY: 'true'
    volumes:
       - ./netdata.conf:/etc/nginx/conf.d/default.conf:ro
       # there are restrictions on /var/run/... so the netdata
       # service can't create a socket either set by systemd or apparmor
       # Debian Bug#946751
       - /var/lib/netdata/:/netdata

volumes:
  certs:
  conf:
  logs:
  passwords:
  proxy-vhosts:
  proxy-html:

networks:
  proxy-network:
   name: global-proxy-network

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

