version: '3.5'

services:

  https-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST:-sammlungsraeume.de}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - passwords:/etc/nginx/htpasswd:ro
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
    networks:
      - default
      - proxy-network

  le-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html

volumes:
  certs:
  passwords:
  proxy-vhosts:
  proxy-html:

networks:
  proxy-network:
   name: global-proxy-network

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

